language: go
go:
- '1.10'
script:
- make check
notifications:
  slack:
    secure: UAhKRUdLbazho+IfXxwhgYYLG5aXLldgEFJWbbg2rVOcAiCNrV16AuG1TtN+BT5BMXHo0V9+IQ0RIT7ENZKfofVvaerWTyI/YEoSHnvtOMRKFTAXXzs3/SP9+kqdPJaY8ssK8SHZ7Va+67U63d2tgW12LXNtAqOgXM8rOKTb5hrOygGURhdCTbgw4V+QHwzbOGqa30Jf1DVek+Qi9LyJL4PLGKamOXQb+YYkVKTMWMRDLTTwEGuwJQ1Qks11Fx5FrD+B+W6p4OzeMICZBpadk64zUvWCiPu21bTC/IOpn5NHS5TJCZNrEQRVMnyyT10KjFxQM3nM5Img1LCGr2bfhsTgUM9C6kg7GDJA432r/DOBXRd36WMuR1g2g2aZQX0xILNt8iWMbVuLH49TVoa+lqtfjXzOnN2A/psss2eCO5eJhk2COJnYvjxlp1R+phAJDaXjSklEKfUx5gM+9Rxj4PTPd26Z7zehqQCPUnOZ00HhyBMpks/qnX1++6mHpHWb9RS+oQ2S78EI2JN2dae/qe5gxfGYaYGYLTEfp9v1tP3cEtfnRJdn2SN3pWsw0btamGxn8YstWOY3WE6Qo+8eWt7R9o/4zYS9bx25KsBZ2miGBgJJF/0TlqcfKvSxtM5z+6VG75NusH2t0L6lAN6WbE04Qpxih58Kf5KINtx0dKA=
